trigger: none
variables:
- group: Variable_group_30-Dec
- name: keyofInfraCost
    Working_path:'$(System.DefaultWorkingDirectory)/enviorment/dev'
pool:
  name : vinod_pool

stages: 
  - stage: build_stage
    displayName: init_validate_Plan
    jobs:
      - job: init_validate
        displayName: init_validate_Plan
        steps: 
        - task: TerraformInstaller@1
          displayName: installer
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: init1
          inputs:
            provider: 'azurerm'
            command: 'init'
            commandOptions: '-upgrade=false'
            workingDirectory: '$(Working_path)'
            backendServiceArm: 'vinod_SC'
            backendAzureRmStorageAccountName: 'vinodstg123'
            backendAzureRmContainerName: 'vinodcontainer'
            backendAzureRmKey: 'dev.terraform.tfstate'

        - task: TerraformTask@5
          displayName: validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(Working_path)'
            environmentServiceNameAzureRM: vinod_SC
        - task: TerraformTask@5
          displayName: Plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(Working_path)'
            environmentServiceNameAzureRM: 'vinod_SC'


        - task: PowerShell@2
          displayName: Install Infracost
          inputs:
                targetType: inline
                script: |
                  Write-Host "Downloading Infracost..."
                  Invoke-WebRequest https://infracost.io/downloads/latest/infracost-windows-amd64.zip -OutFile infracost.zip

                  Write-Host "Extracting Infracost..."
                  Expand-Archive infracost.zip -DestinationPath infracost -Force

                  Write-Host "Checking version..."
                  .\infracost\infracost.exe --version


        - task: PowerShell@2
          displayName: Infra Cost Breakdown
          inputs:
            targetType: inline
            workingDirectory: '$(Working_path)'
            script: |
              Write-Host "Running Infracost breakdown..."
              ..\..\infracost\infracost.exe breakdown `
                --path . `
                --format table
          env:
            INFRACOST_API_KEY: $(keyofInfraCost)


  - stage:
    displayName: scanning_stage
    jobs:
      - job: scanofcode
        displayName: tfsec
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
        
        

  - stage:
    displayName: approval_and_deployment
    jobs:
      - job: manualApproval
        pool: server
        
        displayName: ManualApproval
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'vsondhiya@gmail.com'
            approvers: 'vsondhiya@gmail.com'
            onTimeout: 'resume'

      - job: Apply
        displayName: Apply
        dependsOn: manualApproval
        steps:
        
              
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: latest

        - task: AzureCLI@2
          displayName: Terraform Init
          inputs:
            azureSubscription: vinod_SC
            scriptType: ps
            scriptLocation: inlineScript
            workingDirectory: '$(Working_path)'
            inlineScript: |
              terraform init `
                -backend-config="storage_account_name=vinodstg123" `
                -backend-config="container_name=vinodcontainer" `
                -backend-config="key=dev.terraform.tfstate"
#        - task: TerraformTask@5
#          displayName: apply
#          inputs:
#             provider: 'azurerm'
#             command: 'apply'
#             workingDirectory: '$(Working_path)'
#             environmentServiceNameAzureRM: 'vinod_SC'
            
