trigger: none

pool:
  name : vinod_pool

stages: 
  - stage: build_stage
    displayName: init_validate_Plan
    jobs:
      - job: init_validate
        displayName: init_validate_Plan
        steps: 
        - task: TerraformInstaller@1
          displayName: installer
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: init1
          inputs:
            provider: 'azurerm'
            command: 'init'
            commandOptions: '-upgrade=false'
            workingDirectory: '$(System.DefaultWorkingDirectory)/enviorment/dev'
            backendServiceArm: 'vinod_SC'
            backendAzureRmStorageAccountName: 'vinodstg123'
            backendAzureRmContainerName: 'vinodcontainer'
            backendAzureRmKey: 'dev.terraform.tfstate'

        - task: TerraformTask@5
          displayName: validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/enviorment/dev'
            environmentServiceNameAzureRM: vinod_SC
        - task: TerraformTask@5
          displayName: Plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/enviorment/dev'
            environmentServiceNameAzureRM: 'vinod_SC'

  - stage:
    displayName: Cost_optimization
    jobs:
      - job: costofinfra
        displayName: cost_of_infra
        steps:
        - task: InfracostSetup@2
          inputs:
            apiKey: 'ico-fizfgyE3XeuwWQLPpXwQSK81LjoBfIgS'
            version: '0.10.x'

        - task: CmdLine@2
          displayName: Infra Cost Breakdown
          inputs:
            script: |
              infracost breakdown --path=. --format=table
            workingDirectory: '$(System.DefaultWorkingDirectory)/enviorment/dev'
          env:
            INFRACOST_API_KEY: 'ico-fizfgyE3XeuwWQLPpXwQSK81LjoBfIgS'

  - stage:
    displayName: scanning_stage
    jobs:
      - job: scanofcode
        displayName: tfsec
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
        
        

  - stage:
    displayName: approval_and_deployment
    jobs:
      - job: manualApproval
        pool: server
        
        displayName: ManualApproval
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'vsondhiya@gmail.com'
            approvers: 'vsondhiya@gmail.com'
            onTimeout: 'resume'

      - job: Apply
        displayName: Apply
        dependsOn: manualApproval
        steps:
        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: azurerm
            command: init
            workingDirectory: $(System.DefaultWorkingDirectory)/enviorment/dev
            backendServiceArm: vinod_SC
            backendAzureRmStorageAccountName: vinodstg123
            backendAzureRmContainerName: vinodcontainer
            backendAzureRmKey: dev.terraform.tfstate

        - task: TerraformTask@5
          displayName: apply
          inputs:
             provider: 'azurerm'
             command: 'apply'
             workingDirectory: '$(System.DefaultWorkingDirectory)/enviorment/dev'
             environmentServiceNameAzureRM: 'vinod_SC'
            
